### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by juliancheal** [euruko/euruko2018.github.io#2]
- [x] Domain Name
- [x] DNS of euruko2018.org to point to EuRuKo 2018 Github pages ( https://euruko.github.io/euruko2018.github.io/ )
- [x] Hosting Github pages for landing page/site
- [x] Setup newsletter signup with Mailchimp
- [ ] Link to the previous EuRuKo website ("Looking for EuRuKo 2017?" => www.euruko2017.org)
- [x] Update the design to include the newly-designed banner #6 
- [x] Add the CoC to the landing page #7 
- [x] General euruko.org to point to EuRuKo 2018 GH pages ( https://euruko.github.io/euruko2018.github.io/ )

**Comment by juliancheal** [comment]
Seems http://euruko2018.org is already a thing.

**Comment by acid** [comment]
We can use eurko2018.org and as far as I understood @bai we can just say him which records we would like to set on this domain :)

**Comment by acid** [comment]
We can host the Jekyll sites directly on github. As for newsletter and CfP a Heroku Dyno seems to be a nice idea if they want to support us.

**Comment by bai** [comment]
👋 Would it be possible to host Jekyll on GitHub? This way we'd make sure it's still up here in 5—10 years.

Let me know what DNS entries you need + I'll set up proper redirect from main http://euruko.org website.

**Comment by rousisk** [comment]
We could have the newsletter integration without the need for Heroku... Should we start with Jekyll, GitHub, and Mailchimp and see if we need to upgrade later on?

**Comment by bai** [comment]
> Should we start with Jekyll, GitHub, and Mailchimp and see if we need to upgrade later on?

In my humble opinion that'd be the simplest way. Let me know if there's anything I could do to help.

**Comment by rousisk** [comment]
I've just updated the issue description - @juliancheal I hope you won't mind! - with some more steps until the first beta!

**Comment by dancinglightning** [comment]
Last post subscription redirects to http://www.euruko2018.org/
but that fails, as www cname may not be configured. In other words only http://euruko2018.org/ works

**Comment by acid** [comment]
@dancinglightning thanks for the hint! @bai could you add the cname, please? :)

**Comment by bai** [comment]
Done!
