### ISSUE TITLE
General Assembly 2017-11-03

### ISSUE THREAD

**Issue by acid** [euruko/euruko2018.github.io#3]
## Date & Time
2017-11-03 18:30CET-19:30CET

## Lead
Daniel

## Participants

# proposed Schedule

1. Check-In (5min)
2. Today's Schedule (2min)
3. Regular Meetings (5min)
4. Task Organisation (10min)
5. Organisational umbrella/"Verein"
5. Team structure(?) (? min)
5. Venue News (? min)
6. Sponsoring
5. Childcare
5. Check-Out (5min)

# Notes

**Comment by rousisk** [comment]
Just edited the dates to be ISO8601-formatted instead of the US-style `mm-dd-yy` so there's no room for confusion and misinterpretation down the road :-)
